services:
  jump-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: sshutil-jump
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      - USER_NAME=jumpuser
      - USER_PASSWORD=jumppass
      - PASSWORD_ACCESS=true
      - SUDO_ACCESS=true
    ports:
      - "2222:2222"
    restart: unless-stopped

  target-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: sshutil-target
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      - USER_NAME=targetuser
      - USER_PASSWORD=targetpass
      - PASSWORD_ACCESS=true
      - SUDO_ACCESS=true
    ports:
      - "2223:2222" # target server ssh port is 2223 on host
    restart: unless-stopped
